apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qaf3xu2pj-python 
  janus-idp.io/tekton: qaf3xu2pj-python
  backstage.io/kubernetes-id: qaf3xu2pj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qaf3xu2pj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml