apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qaf3xu2pj-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qaf3xu2pj-python 
  name: qaf3xu2pj-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: qaf3xu2pj-python 
